extends: ./config.yaml
configs:
  uriGroup:
    portal:
      uri: http://localhost:4200/portal
      type: redirect
    site:
      uri: http://localhost:4200/site
      type: redirect
    api:
      uri: http://localhost:4200/api
  redius:
    enabled: false
    host: http://127.0.0.1
    port: 1234
  cluster:
    enabled: true
    maxCpuNum: 1
